name: my-aqua-installer
description: 'checkout>aqua-installer'
inputs:
  aqua_opts:
    description: https://aquaproj.github.io/docs/products/aqua-installer/
    required: false
    default: "-l"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: aquaproj/aqua-installer@v2.3.0
      with:
        aqua_version: v2.22.0
        aqua_opts: ${{ inputs.aqua_opts }}
